### ISSUE TITLE
cant get it to install

### ISSUE THREAD

**Issue by jonathanrcarter** [himaxwell/equifax-ruby#4]
Hi , 

I keep getting this

Jonathan-Carters-MacBook-Air-2:equifax-ruby-master jc$ gem install equifax-ruby 
ERROR:  Could not find a valid gem 'equifax-ruby' (>= 0) in any repository

I am not a ruby guy but I want to use your code, so it can be a beginners mistake (sorry if it is... :-) ) 

Jonathan

**Comment by JamesDullaghan** [comment]
@jonathanrcarter Hey Jonathan, apologies for missing this.

This gem has not been pushed to rubygems. You can point to the github repo in your project with the following:

`gem 'equifax-ruby', git: 'https://github.com/himaxwell/equifax-ruby.git'`

or fork the repo and use your own git url.

Thanks!
